package com.captain.allowanceos

enum class ServiceCategory {
    AGENT,
    RESEARCH,
    SIGNALS,
    AUTOMATION,
    API,
}

data class CommercialServiceTemplate(
    val id: String,
    val icon: String,
    val name: String,
    val nameZh: String,
    val category: ServiceCategory,
    val categoryZh: String,
    val summary: String,
    val summaryZh: String,
    val merchant: String,
    val token: String = "USDC",
    val perCharge: Double,
    val periodCap: Double,
    val billingPeriod: String,
    val billingPeriodZh: String,
    val evidenceRequirement: String,
    val evidenceRequirementZh: String,
    val allowedProgram: String,
    val riskTier: String,
) {
    fun toPolicy() = AllowancePolicy(
        allowanceId = "allowance-$id-001",
        merchant = merchant,
        token = token,
        perChargeCap = perCharge,
        periodCap = periodCap,
        program = allowedProgram,
    )
}

data class SeekerIntegrationBlueprint(
    val appName: String,
    val icon: String,
    val useCase: String,
    val useCaseZh: String,
    val allowancePattern: String,
    val allowancePatternZh: String,
    val adapterRequirement: String,
    val adapterRequirementZh: String,
    val sourceUrl: String,
)

object CommercialCatalog {
    const val DEFAULT_ID = "alphabrief"

    val templates = listOf(
        CommercialServiceTemplate(
            id = "agentcloud",
            icon = "AI",
            name = "AgentCloud",
            nameZh = "AgentCloud 智能体",
            category = ServiceCategory.AGENT,
            categoryZh = "AI Agent 订阅",
            summary = "A monthly operating budget for an autonomous research agent.",
            summaryZh = "为自主研究 Agent 设置可撤销的月度运行预算。",
            merchant = "merchant:agentcloud",
            perCharge = 0.50,
            periodCap = 12.0,
            billingPeriod = "Monthly · metered runs",
            billingPeriodZh = "按月 · 按调用计费",
            evidenceRequirement = "Signed run receipt + output hash",
            evidenceRequirementZh = "签名运行回执 + 输出哈希",
            allowedProgram = "program:agentcloud-settlement",
            riskTier = "MEDIUM",
        ),
        CommercialServiceTemplate(
            id = DEFAULT_ID,
            icon = "R",
            name = "AlphaBrief",
            nameZh = "AlphaBrief 研究报告",
            category = ServiceCategory.RESEARCH,
            categoryZh = "研究报告",
            summary = "Pay per delivered report only after its content hash is bound.",
            summaryZh = "仅在报告内容哈希完成绑定后按篇付费。",
            merchant = "merchant:alphabrief",
            perCharge = 2.0,
            periodCap = 8.0,
            billingPeriod = "Weekly · up to 4 reports",
            billingPeriodZh = "每周 · 最多 4 份报告",
            evidenceRequirement = "Report URI + SHA-256 content hash",
            evidenceRequirementZh = "报告 URI + SHA-256 内容哈希",
            allowedProgram = "Memo111111111111111111111111111111111111111",
            riskTier = "LOW",
        ),
        CommercialServiceTemplate(
            id = "signalwire",
            icon = "S",
            name = "SignalWire",
            nameZh = "SignalWire 交易信号",
            category = ServiceCategory.SIGNALS,
            categoryZh = "交易信号",
            summary = "A capped signal feed that cannot silently change publisher identity.",
            summaryZh = "限制交易信号订阅额度，并禁止发布者身份静默变更。",
            merchant = "merchant:signalwire",
            perCharge = 0.25,
            periodCap = 5.0,
            billingPeriod = "Daily · max 20 signals",
            billingPeriodZh = "每日 · 最多 20 条信号",
            evidenceRequirement = "Timestamped signal hash + publisher signature",
            evidenceRequirementZh = "带时间戳的信号哈希 + 发布者签名",
            allowedProgram = "program:signal-delivery",
            riskTier = "MEDIUM",
        ),
        CommercialServiceTemplate(
            id = "autopilot",
            icon = "AP",
            name = "AutoPilot",
            nameZh = "AutoPilot 自动交易",
            category = ServiceCategory.AUTOMATION,
            categoryZh = "自动化交易机器人",
            summary = "Separate execution authority from bounded fee and strategy budgets.",
            summaryZh = "把交易执行权与机器人费用、策略预算严格分离。",
            merchant = "merchant:autopilot",
            perCharge = 1.0,
            periodCap = 20.0,
            billingPeriod = "Weekly · execution fees only",
            billingPeriodZh = "每周 · 仅限执行费用",
            evidenceRequirement = "Strategy ID + order receipt + verifier hash",
            evidenceRequirementZh = "策略 ID + 订单回执 + 验证器哈希",
            allowedProgram = "program:autopilot-fees",
            riskTier = "HIGH",
        ),
        CommercialServiceTemplate(
            id = "datapipe",
            icon = "API",
            name = "DataPipe",
            nameZh = "DataPipe 付费 API",
            category = ServiceCategory.API,
            categoryZh = "付费 API",
            summary = "Meter API usage without exposing an unlimited wallet approval.",
            summaryZh = "按 API 用量结算，同时避免向服务方开放无限钱包授权。",
            merchant = "merchant:datapipe",
            perCharge = 0.05,
            periodCap = 10.0,
            billingPeriod = "Monthly · metered requests",
            billingPeriodZh = "按月 · 按请求量计费",
            evidenceRequirement = "Usage batch root + signed metering receipt",
            evidenceRequirementZh = "用量批次根 + 签名计量回执",
            allowedProgram = "program:api-metering",
            riskTier = "LOW",
        ),
    )

    fun byId(id: String): CommercialServiceTemplate = templates.firstOrNull { it.id == id }
        ?: templates.first { it.id == DEFAULT_ID }

    val seekerBlueprints = listOf(
        SeekerIntegrationBlueprint(
            appName = "Helium Mobile",
            icon = "HM",
            useCase = "Recurring mobile plan and add-on data allowances.",
            useCaseZh = "移动套餐与附加流量的周期授权。",
            allowancePattern = "Monthly cap + merchant binding + service-period receipt",
            allowancePatternZh = "月度上限 + 商户绑定 + 服务周期回执",
            adapterRequirement = "Merchant billing adapter must emit a signed service receipt.",
            adapterRequirementZh = "商户计费适配器需要输出签名服务回执。",
            sourceUrl = "https://solanamobile.com/blog/seeker-season-10-dapps-you-should-download-right-now",
        ),
        SeekerIntegrationBlueprint(
            appName = "Parallel Colony",
            icon = "PC",
            useCase = "Game season pass, optional AI actions, and bounded item budgets.",
            useCaseZh = "游戏季票、可选 AI 行动与道具消费预算。",
            allowancePattern = "Season expiry + category limits + explicit high-value confirmation",
            allowancePatternZh = "赛季到期 + 分类额度 + 高价值消费二次确认",
            adapterRequirement = "Game backend must bind entitlement or item delivery evidence.",
            adapterRequirementZh = "游戏后端需要绑定权益或道具交付证明。",
            sourceUrl = "https://solanamobile.com/blog/seeker-season-10-dapps-you-should-download-right-now",
        ),
        SeekerIntegrationBlueprint(
            appName = "Amp Pay",
            icon = "AP",
            useCase = "Merchant subscriptions and repeat purchases with clear revocation.",
            useCaseZh = "支持商户订阅与可随时撤销的重复购买。",
            allowancePattern = "Merchant-scoped allowance + receipt hash + purchase cap",
            allowancePatternZh = "商户范围授权 + 回执哈希 + 购买上限",
            adapterRequirement = "Checkout adapter must request an Allowance OS pre-flight decision.",
            adapterRequirementZh = "结账适配器需要先请求 Allowance OS 策略预检。",
            sourceUrl = "https://solanamobile.com/blog/seeker-season-10-dapps-you-should-download-right-now",
        ),
        SeekerIntegrationBlueprint(
            appName = "Moonwalk Fitness",
            icon = "MW",
            useCase = "Membership, challenge entry, and reward-service fees.",
            useCaseZh = "会员、挑战报名与奖励服务费用。",
            allowancePattern = "Challenge expiry + fixed entry cap + outcome receipt",
            allowancePatternZh = "挑战到期时间 + 固定报名上限 + 结果回执",
            adapterRequirement = "Challenge contract or API must expose fulfillment evidence.",
            adapterRequirementZh = "挑战合约或 API 需要提供履约证据。",
            sourceUrl = "https://solanamobile.com/blog/seeker-season-10-dapps-you-should-download-right-now",
        ),
        SeekerIntegrationBlueprint(
            appName = "Perena",
            icon = "P",
            useCase = "Bounded automation fees for stable-asset workflows.",
            useCaseZh = "为稳定资产自动化流程设置受限服务费。",
            allowancePattern = "Program allowlist + fee-only cap + transaction evidence",
            allowancePatternZh = "程序白名单 + 仅费用额度 + 交易证据",
            adapterRequirement = "Protocol adapter must separate principal from service fees.",
            adapterRequirementZh = "协议适配器必须区分本金与服务费用。",
            sourceUrl = "https://solanamobile.com/blog/seeker-season-10-dapps-you-should-download-right-now",
        ),
    )
}
